<a href="https://colab.research.google.com/github/thakurvishalsingh1260/python/blob/main/numpymatrix_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
#Addition
import numpy as np
x=([6,4,3],[23,45,67])
y=([43,41,35],[23,19,10])
add1=np.add(x,y)
print(add1)

[[49 45 38]
 [46 64 77]]


In [57]:
#Substraction
import numpy as np
x=([6,4,3],[23,45,67])
y=([43,41,35],[23,19,10])
sub=np.subtract(x,y)
print(sub1)

[[-37 -37 -32]
 [  0  26  57]]


In [58]:
#Multiplication
import numpy as np
x=([6,4,3],[23,45,67],[2,4,8])
y=([43,41,35],[23,19,10],[5,7,1])
mul=np.dot(x,y)
print(mul)

[[ 365  343  253]
 [2359 2267 1322]
 [ 218  214  118]]


In [59]:
#Divide
div=np.divide(x,y)
print(div)

[[0.13953488 0.09756098 0.08571429]
 [1.         2.36842105 6.7       ]
 [0.4        0.57142857 8.        ]]


In [60]:
#transpose
trans=np.transpose(x)
print(trans)

[[ 6 23  2]
 [ 4 45  4]
 [ 3 67  8]]
